{"name": "test_xfail", "status": "skipped", "statusDetails": {"message": "XFAIL 修复后移除此标记\n\nAssertionError: assert 1 == 2", "trace": "@pytest.mark.xfail(strict=True,reason=\"修复后移除此标记\")\n    def test_xfail():\n        a = 1\n>       assert a == 2\nE       assert 1 == 2\n\ntest_markers_practice.py:22: AssertionError"}, "start": 1745633394995, "stop": 1745633394995, "uuid": "8e07b5c7-7dc1-483c-9ad6-e42666de87f6", "historyId": "a5479ccfd1b253c5beb9609634722e32", "testCaseId": "a5479ccfd1b253c5beb9609634722e32", "fullName": "test_markers_practice#test_xfail", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(strict=True, reason='修复后移除此标记')"}, {"name": "suite", "value": "test_markers_practice"}, {"name": "host", "value": "192.168.1.5"}, {"name": "thread", "value": "60617-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_markers_practice"}]}